function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	msg.post("/Camera#camera", "acquire_camera_focus")
	local bool_value = true
	--defos.set_fullscreen(bool_value)
	defos.toggle_fullscreen()
	bool_value = defos.is_fullscreen()
	print(bool_value)
end

function on_input(self, action_id, action)
	if action_id == hash("LMB") and action.pressed then
		print("Touch!")
	end
end
